<#
.SYNOPSIS
  DSH Web 开机自启一键安装（隐藏后台运行）
.DESCRIPTION
  自动检测 node / dsh 路径，生成 start-dsh.bat 与 start-dsh-web.vbs，
  注册计划任务（登录时触发、wscript 隐藏窗口运行，零弹窗）。
  需要管理员权限（注册计划任务）；脚本会自动请求提权。
.PARAMETER Port
  服务端口，默认 10101
.PARAMETER WorkDir
  工作目录（会话归属），默认当前目录
.PARAMETER InstallDir
  脚本安装目录，默认 $env:USERPROFILE\.dsh-tools
.PARAMETER EnableLan
  附加 --trusted-host <局域网IP>（配合 80 端口代理使用），默认关闭
.EXAMPLE
  powershell -ExecutionPolicy Bypass -File setup.ps1
  powershell -ExecutionPolicy Bypass -File setup.ps1 -Port 10101 -EnableLan
#>
param(
  [int]$Port = 10101,
  [string]$WorkDir = (Get-Location).Path,
  [string]$InstallDir = (Join-Path $env:USERPROFILE ".dsh-tools"),
  [switch]$EnableLan
)
$ErrorActionPreference = "Stop"

# --- 自提权（注册计划任务需要管理员）---
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Write-Host "需要管理员权限，正在请求提权..." -ForegroundColor Yellow
  Start-Process powershell -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Port $Port -WorkDir `"$WorkDir`" -InstallDir `"$InstallDir`"" + $(if ($EnableLan) { " -EnableLan" } else { "" })
  exit
}

# --- 检测 node ---
$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node -or -not (Test-Path $node)) {
  $node = "C:\Program Files\nodejs\node.exe"
}
if (-not (Test-Path $node)) { throw "找不到 node.exe，请先安装 Node.js (https://nodejs.org)" }

# --- 检测 dsh bin.js ---
$binJs = $null
$dshCmd = Get-Command dsh -ErrorAction SilentlyContinue
if ($dshCmd) {
  $shimDir = Split-Path $dshCmd.Source -Parent
  foreach ($cand in @(
    (Join-Path $shimDir "node_modules\@deepseek-ai\dsh\lib\bin.js"),
    (Join-Path $shimDir "@deepseek-ai\dsh\lib\bin.js")
  )) { if (Test-Path $cand) { $binJs = $cand; break } }
}
if (-not $binJs) {
  $cand = Join-Path $env:APPDATA "npm\node_modules\@deepseek-ai\dsh\lib\bin.js"
  if (Test-Path $cand) { $binJs = $cand }
}
if (-not $binJs) { throw "找不到 dsh 的 bin.js，请确认已安装: npm i -g @deepseek-ai/dsh" }

Write-Host "node : $node"
Write-Host "dsh  : $binJs"
Write-Host "port : $Port"
Write-Host "dir  : $InstallDir"

# --- 生成 start-dsh.bat ---
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
$log = Join-Path $env:USERPROFILE ".dsh\web-autostart.log"
$lanArgs = if ($EnableLan) { " --trusted-host %LANIP%" } else { "" }

$batTemplate = @'
@echo off
rem DSH Web launcher (generated by dsh-web-autostart setup.ps1)
set "NODE=__NODE__"
set "DSH_BIN=__BINJS__"
set "LOG=__LOG__"
set "PORT=__PORT__"
cd /d "__WORKDIR__"

netstat -ano | findstr /c:":__PORT__ " | findstr /c:"LISTENING" >nul 2>&1
if not errorlevel 1 (
  echo %date% %time% : port __PORT__ already in use, skipping start >> "%LOG%"
  exit /b 0
)

rem Detect LAN IPv4 (adapter with a default gateway) for --trusted-host
set "LANIP="
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "(Get-NetIPConfiguration | Where-Object {$_.IPv4DefaultGateway -ne $null}).IPv4Address.IPAddress"`) do set "LANIP=%%i"

echo %date% %time% : starting dsh web on port __PORT__ (LAN: %LANIP%) >> "%LOG%"
"%NODE%" "%DSH_BIN%" web --port %PORT%__LAN_ARGS__ >> "%LOG%" 2>&1
'@
$bat = $batTemplate
  .Replace("__NODE__", $node)
  .Replace("__BINJS__", $binJs)
  .Replace("__LOG__", $log)
  .Replace("__PORT__", "$Port")
  .Replace("__WORKDIR__", $WorkDir)
  .Replace("__LAN_ARGS__", $lanArgs)
$batPath = Join-Path $InstallDir "start-dsh.bat"
Set-Content -Path $batPath -Value $bat -Encoding ASCII

# --- 生成 start-dsh-web.vbs（隐藏窗口）---
$vbs = @'
Set sh = CreateObject("WScript.Shell")
sh.Run "cmd /c ""__BAT__""", 0, False
'@
$vbs = $vbs.Replace("__BAT__", $batPath)
$vbsPath = Join-Path $InstallDir "start-dsh-web.vbs"
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII

# --- 注册计划任务 ---
$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsPath`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero)
Register-ScheduledTask -TaskName "DSH Web Autostart" -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "Starts DSH Web hidden at logon." -Force | Out-Null

# --- 完成 ---
Write-Host ""
Write-Host "=== 安装完成 ===" -ForegroundColor Green
Write-Host "端口     : $Port"
Write-Host "启动脚本 : $batPath"
Write-Host "隐藏启动 : $vbsPath"
Write-Host "日志     : $log"
Write-Host "任务     : DSH Web Autostart（登录触发，隐藏运行）"
if ($EnableLan) {
  Write-Host "局域网   : 已附加 --trusted-host（还需配 80 端口代理 + 防火墙，见 SKILL.md）"
}
Write-Host ""
Write-Host "下一步：重启电脑（或双击 $vbsPath 立即测试），然后浏览器打开 http://127.0.0.1:$Port"
Write-Host "桌面快捷方式：见 SKILL.md（Win11 需手动右键固定到任务栏）"
